[tool.poetry]
name = "hackerrank"
version = "0.1.0"
description = ""
authors = ["Simon <samnaka@naver.com>"]

[tool.poetry.dependencies]
python = "^3.7"
black = "^21.4b2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
